Update S50wireguard
Update information displayed when '-h|help' command requested - Thanks SNB Forum member @Torson

Consolidate 'Restart' code with 'Start' code.

NOTE:  'wgm start' will start ALL defined  WireGuard Peers in '/jffs/configs/WireguardVPN_map'
             but
            'wgm restart' will only restart ACTIVE WireGuard Peers.

Unify progress message formats i.e. scripts S50wireguard,wg_manager.sh, and wg_server  should now look consistent. 

Fix: Allow fornon-standard WireGuards Peer configurations i.e. 'SGS8' or 'wg0-clientUSA' etc.

diff --git a/S50wireguard b/S50wireguard
--- a/S50wireguard
+++ b/S50wireguard
@@ -1,8 +1,8 @@
 #!/bin/sh
-VERSION="v1.08"
-#============================================================================================ © 2021 Martineau v1.08
+VERSION="v1.09"
+#============================================================================================ © 2021 Martineau v1.09
 #
-#       S50wireguard   {start|stop|restart|check|create} [ [client [policy] |server]} [wg_instance] ]
+#       S50wireguard   {start|stop|restart|show|create} [ [client [policy|nopolicy] |server]} [wg_instance] ]
 #
 #       S50wireguard   start 0
 #                      Initialises remote peer 'client' 'wg0'
@@ -24,7 +24,7 @@ VERSION="v1.08"
 #
 
 # Maintainer: Martineau
-# Last Updated Date: 05-Mar-2021
+# Last Updated Date: 06-Mar-2021
 #
 # Description:
 #
@@ -39,22 +39,6 @@ GITHUB_DIR=$GITHUB_MARTINEAU                       # default for script
 CONFIG_DIR="/opt/etc/wireguard/"
 CHECK_GITHUB="1"
 SILENT="s"                                         # Default is no progress messages for file downloads
-
-
-
-
-#Mode=client   #server or client
-
-#server
-#export Subnet=   #e.g.)10.50.50.1/24
-#export wgport=
-
-#client
-#export LocalIP=  #e.g.)10.50.50.2
-
-#Route=default   #default or policy
-#export wgdns=
-#export Nipset=wgvpn
 
 Say(){
    echo -e $$ $@ | logger -st "($(basename $0))"
@@ -383,8 +367,8 @@ wg13    N      xxx.xxx.xxx.xxx/32    103.231.88.18:51820    193.138.218.74    # 
 wg14    N      xxx.xxx.xxx.xxx/32    193.32.126.66:51820    193.138.218.74    # Mullvad France, Paris
 wg15
 
-wg21    Y      xxx.50.1.1/24                                                  # $HARDWARE_MODEL Local Host Peer 1
-wg22    N      xxx.50.2.1/24                                                  # $HARDWARE_MODEL Local Host Peer 2
+wg21    Y      xxx.50.1.1/24         <<= DHCP Pool                            # $HARDWARE_MODEL Local Host Peer 1
+wg22    N      xxx.50.2.1/24         <<= DHCP Pool                            # $HARDWARE_MODEL Local Host Peer 2
 
 # The following default 'wg0' interface retained for backward compatibility!
 wg0     N      xxx.xxx.xxx.xxx/32     86.106.143.93:51820    193.138.218.74    # Mullvad USA, New York
@@ -397,7 +381,12 @@ rp13
 rp14
 rp15    <Router>192.168.1.0/24>>VPN<LAN>192.168.1.1>>WAN
 
+# Custom 'client' Peer interfaces - simply to annotate
+SGS8    N      1.2.3.4            xxx.xxx.xxx.xxx        dns.xxx.xxx.xxx    # A comment here
+wg0-client5 N  4.3.2.1                                                      # Mullvad UK, London
+
 # Optionally define the 'server' Peer 'clients' so they can be identified by name in the enhanced WireGuard Peer status report
+# These entries are automatically added below when the 'create' command is used.
 # Public Key                                      DHCP IP             Annotation Comment
 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=      10.50.1.1           # A Cell phone
 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=      10.50.1.88          # Samsung Galaxy S8
@@ -457,6 +446,32 @@ EOF
     echo -e $cBGRE"\n\tnat-start updated"$cRESET
     SayT "nat-start updated"
 }
+Server_or_Client() {                                                                    # v1.09
+
+    local WG_INTERFACE=$1
+
+    # Is this a standard 'client' Peer interface 'wg11-wg15' or 'server' 'wg21-wg22'    # v1.09
+    if [ -z "$(echo "$WG_INTERFACE" | grep -oE "^wg[2][1-2]|^wg[1][1-5]*$")" ];then     # v1.09
+        # Non-stand so identfy if it's a 'client' or 'server' Peer
+        if [ -f ${CONFIG_DIR}${WG_INTERFACE}.conf ];then                                # v1.03
+            if [ -n "$(grep -iE "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)" ];then  # v1.03
+                local Mode="client"
+            else
+                local Mode="server"
+            fi
+        fi
+    fi
+    echo "$Mode"
+}
+WG_show() {
+
+    local SHOW=$1
+
+    if [ "$SHOW" == "Y" ];then
+        echo -e $cBCYA"\tStatus:\n"$cRESET
+        /opt/bin/wg show all
+    fi
+}
 
 #For verbose debugging, uncomment the following two lines, and uncomment the last line of this script
 #set -x
@@ -485,8 +500,6 @@ if [ "$(nvram get ntp_ready)" = "0" ];then              # Ensure event 'restart_
     [ -z "$(grep "wireguard" $FN)" ] && echo -e "if [ "\$2" = "diskmon" ]; then { sh /opt/etc/init.d/S50wireguard start & } ; fi # wireguard" >> $FN
     Say "$VERSION WireGuard delayed for NTP synch event trigger 'restart_diskmon' [$@]"
     exit 99
-#else
-    #Say "$VERSION $1 WireGuard NTP is Ready"
 fi
 
 [ "$1" == "debug" ] && { shift; set -x; }
@@ -499,106 +512,75 @@ TYPE=$2
 
 if [ -n "$(echo "start|stop|restart" | grep -o "$ACTION")" ];then
 
-    if [ -z "$TYPE" ];then
-        TYPE="client"
-    else
-        if [ -f "${CONFIG_DIR}${TYPE}.conf" ];then          # Is it an interface name? e.g. 'SGS8' or 'wg-client0'
-            WG_INTERFACE=$TYPE
-            [ -z "$(grep -E "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)" ] && TYPE="server" || TYPE="client"
+    if [ -z "$2" ];then
+        WG_INTERFACE=
+
+        # If no specific Peer specified, for Restart retrieve ACTIVE Peers otherwise for Stop/Start use Peer configuration
+        if [ "$ACTION" != "restart" ];then                  # v1.09
+            AUTO_PEERS=$(awk '$2 == "Y" || $2 =="P" {print $1}' /jffs/configs/WireguardVPN_map| tr '\n#' ' ')
+        else
+            AUTO_PEERS=$(wg show interfaces)                # v1.09
         fi
+        echo -e
+    else
+        echo -en $cBCYA
+        case "$2" in
+            client|server)
+
+                if [ -z "$3" ];then
+                    echo -en $cBRED"\a\n\t***ERROR: missing WireGuard Peer interface\n"$cRESET
+                    exit 97
+                fi
+
+                WG_INTERFACE=$3
+
+            ;;
+            *)
+                WG_INTERFACE=$3
+
+            ;;
+        esac
     fi
 
-    case "$TYPE" in
-        server|1)
-            Mode="server"
-            if [ -z "$WG_INTERFACE" ];then
-                if [ -z "$3" ];then
-                    WG_INTERFACE="wg1"
-                    export $WG_INTERFACE
-                    export Subnet=10.50.1.1/24
-                    export wgport=1150
-                else
-                    WG_INTERFACE="wg2"$3
-                    export $WG_INTERFACE
-                    export Subnet=10.50.$3.1/24
-                    export wgport="115"$3
-                fi
-            fi
-            ;;
-        *)
-            Mode=client
-
-            if [ -z "$WG_INTERFACE" ];then
-                if [ -z "$2" ] || [ "$2" == "0" ] || [ "$3" == "0" ];then
-                    WG_INTERFACE="wg0"
-                    export $WG_INTERFACE
-                    #export LocalIP=10.160.107.63/8  # Martineau https://tunsafe.com/vpn  Account Number    57937020164277392089
-                    Route=default
-                else
-                    if [ "$2" == "client" ];then
-                        INDEX=$3
-                    else
-                        INDEX=$2
-                    fi
-                    case $INDEX in
-                        1|2|3|4|5)
-                                    WG_INTERFACE="wg1"$INDEX
-                                    #export WG_INTERFACE=$WG_INTERFACE
-                                    export Subnet=10.50.$INDEX.1/24
-                                    export wgport="115"$INDEX
-
-                    ;;
-                    *)
-                        echo -en $cRED"\a\n\t";Say "$VERSION Missing/Invalid VPN ID '$INDEX' e.g. range 0 - 5 ";echo -e $cRESET
-                        exit 99
-                    ;;
-                    esac
-                fi
-            fi
-
-            # Read the Remote peer config to set the LOCAL peer endpoint
-            if [ -f /jffs/configs/WireguardVPN_map ];then
-                LOCALIP=$(awk -v pattern="$WG_INTERFACE" 'match($0,"^"pattern) {print $2}' /jffs/configs/WireguardVPN_map)
-                export LocalIP=$LOCALIP
-                SOCKET=$(awk -v pattern="$WG_INTERFACE" 'match($0,"^"pattern) {print $4}' /jffs/configs/WireguardVPN_map)
-                DESC=$(awk -v pattern="$WG_INTERFACE" 'match($0,"^"pattern) {print $0}' /jffs/configs/WireguardVPN_map | grep -oE "#.*$" | sed 's/^[ \t]*//;s/[ \t]*$//')
-            fi
-
-            if [ "$3" == "policy" ] || [ "$3" == "policy" ];then
-                Route="policy"
-            fi
-
-            ;;
-    esac
-
     case "$ACTION" in
-        start)
+        start|restart)                                  # v1.09
 
-            if [ -z "$2" ];then
-                WG_INTERFACE=
-                # The AUTO flag may be 'Y' or 'P' to indicate if auto policy is required
-                AUTO_PEERS=$(awk '$2 == "Y" || $2 =="P" {print $1}' /jffs/configs/WireguardVPN_map| tr '\n#' ' ')
+            if [ -n "$AUTO_PEERS" ];then
+                Say "$VERSION Requesting WireGuard VPN Peer auto-$ACTION ($AUTO_PEERS)"
                 echo -e
-                [ -n "$AUTO_PEERS" ] && { Say "$VERSION Requesting WireGuard VPN Peer auto-start ($AUTO_PEERS)"; echo -e; }
             else
-                echo -en $cBCYA
-                Say "$VERSION Requesting WireGuard VPN '$Mode' Peer ('$WG_INTERFACE') $DESC."
-                echo -en $cRESET
+                Mode=$(Server_or_Client "$WG_INTERFACE")
             fi
 
-            for WG_INTERFACE in $AUTO_PEERS $WG_INTERFACE
-                do
-                    [ "$(awk -v pattern="$WG_INTERFACE" 'match($0,"^"pattern) {print $2}' /jffs/configs/WireguardVPN_map)" == "P" ] && Route="policy" || Route="default"
+            # Commandline request overrides entry in config file                            # v1.09
+            [ -n "$(echo "$@" | grep "nopolicy")" ] && Route="default"                      # v1.09
+            [ -n "$(echo "$@" | grep "policy")" ] && { Route="policy"; POLICY_MODE="Policy Mode"; } || Route="default"      # v1.09
 
+            echo -e
+
+            for WG_INTERFACE in $WG_INTERFACE $AUTO_PEERS
+                do
+                    if [ -z "$Route" ];then
+                        [ "$(awk -v pattern="$WG_INTERFACE" 'match($0,"^"pattern) {print $2}' /jffs/configs/WireguardVPN_map)" == "P" ] && Route="policy" || Route="default"
+                    fi
+
+                    if [ "$ACTION" == "restart" ];then                                      # v1.09
+                        if [ -n "$(ifconfig $WG_INTERFACE 2>/dev/null | grep inet)" ];then  # v1.09
+                            Mode=$(grep -iE "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)  # v1.09
+                            echo -e $cBWHT;Say "$VERSION Restarting Wireguard VPN '$Mode' Peer ($WG_INTERFACE)"
+                            [ "$Mode" == "server" ] && ${CONFIG_DIR}wg_server $WG_INTERFACE "disable" || ${CONFIG_DIR}wg_manager.sh $WG_INTERFACE "disable"                 # v1.09
+                        fi
+                    fi
+
+                    echo -en $cBCYA
+                    SayT "$VERSION Initialising Wireguard VPN '$Mode' Peer ($WG_INTERFACE) ${POLICY_MODE}"
                     if [ -n "$(ifconfig | grep -E "^$WG_INTERFACE")" ];then
-                        echo -en $cBWHT
-                        Say "Initialising Wireguard VPN $MODE Peer ($VPN_ID) ${POLICY_MODE}${TXT} $SOCKET ($DESC)";echo -en $cRESET
-                        echo -en $cRED"\a\t";Say "WireGuard VPN '$Mode' Peer ('$WG_INTERFACE') ALREADY ACTIVE";echo -e $cRESET
+                        SayT "***ERROR: WireGuard '$Mode' Peer ('$WG_INTERFACE') ALREADY ACTIVE"
+                        echo -e $cRED"\a\t***ERROR: WireGuard '$Mode' Peer (${cBWHT}$WG_INTERFACE${cBRED}) ALREADY ACTIVE\n"$cRESET
                     else
                         if [ -f ${CONFIG_DIR}${WG_INTERFACE}.conf ];then
-
                             # Rather than rely on naming convention; verify the content
-                            [ -z "$(grep -E "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)" ] && Mode="server" || Mode="client"
+                            [ -z "$(grep -iE "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)" ] && Mode="server" || Mode="client"
 
                             if [ "$Mode" == "server" ] ; then
                                 ${CONFIG_DIR}wg_server $WG_INTERFACE
@@ -609,40 +591,39 @@ if [ -n "$(echo "start|stop|restart" | grep -o "$ACTION")" ];then
                                     ${CONFIG_DIR}wg_manager.sh $WG_INTERFACE "policy"
                             fi
                         else
-                            echo -en $cBRED"\a\n\t";Say "WireGuard VPN '$Mode' Peer ('$WG_INTERFACE') config NOT found?....skipping start request"
-                            echo -e $cRESET
+                            [ -n "$Mode" ] && TXT="'$Mode' " || TXT=            # v1.09
+                            SayT "***ERROR: WireGuard VPN ${TXT}Peer ('$WG_INTERFACE') config NOT found?....skipping $ACTION request"
+                            echo -e $cBRED"\a\tWireGuard ${TXT}Peer (${cBWHT}$WG_INTERFACE${cBRED}) config NOT found?....skipping $ACTION request\n"$cRESET     # v1.09
                         fi
-
                     fi
                 done
-            echo -e $cBCYA"\tStatus:\n"$cRESET
-            /opt/bin/wg show all
+            WG_show
             ;;
         stop)
-
-            #logger -s "Stopping WireGuard service."
 
             if [ -z "$2" ];then
                 AUTO_PEERS=$(wg show interfaces)
                 if [ -n "$AUTO_PEERS" ];then
                     WG_INTERFACE=
-                    echo -en $cBWHT"\n";Say "$VERSION Requesting termination of Active WireGuard VPN Peers ($AUTO_PEERS)"
-                    echo -e $cRESET
+                    echo -en $cBWHT;Say "$VERSION Requesting termination of Active WireGuard VPN Peers ($AUTO_PEERS)"
+                    echo -en $cRESET
                 else
-                    echo -en $cRED"\a\n\t"
-                    Say "No WireGuard VPN peers Active"
+                    echo -en $cRED"\a\t"
+                    Say "No WireGuard VPN Peers Active"
                     echo -e
-                    exit 97
+                    exit 0
                 fi
             fi
 
-            for WG_INTERFACE in $AUTO_PEERS $WG_INTERFACE
+            echo -e
+
+            for WG_INTERFACE in $WG_INTERFACE $AUTO_PEERS
                 do
-                    #${CONFIG_DIR}/wg-down
-                    [ -z "$(grep -E "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)" ] && Mode="server" || Mode="client"
+                    [ -z "$(grep -iE "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)" ] && Mode="server" || Mode="client"
 
                     DESC=$(awk -v pattern="$WG_INTERFACE" 'match($0,"^"pattern) {print $0}' /jffs/configs/WireguardVPN_map | grep -oE "#.*$" | sed 's/^[ \t]*//;s/[ \t]*$//')
-                    Say "$VERSION Requesting termination of WireGuard VPN '$Mode' Peer ('$WG_INTERFACE') $DESC."
+                    echo -en $cBCYA
+                    Say "$VERSION Requesting termination of WireGuard VPN '$Mode' Peer ('$WG_INTERFACE')"
 
                     if [ -z "$(ifconfig | grep -E "^$WG_INTERFACE")" ];then
                         echo -e $cRED"\a\t";Say "WireGuard VPN '$Mode' Peer ('$WG_INTERFACE') NOT ACTIVE";echo -e
@@ -662,28 +643,7 @@ if [ -n "$(echo "start|stop|restart" | grep -o "$ACTION")" ];then
                     fi
                 done
 
-            /opt/bin/wg show all
-
-            ;;
-        restart)
-
-            [ -n "$(ifconfig $WG_INTERFACE 2>/dev/null | grep inet)" ] && { Say "$VERSION Restarting WireGuard VPN '$Mode' Peer ('$WG_INTERFACE') $DESC"; ${CONFIG_DIR}wg_server $WG_INTERFACE "disable"; sleep 1; }
-
-            if [ "$Mode" == "server" ] ; then
-
-                ${CONFIG_DIR}wg_server $WG_INTERFACE "disable"
-                ${CONFIG_DIR}wg_server $WG_INTERFACE
-
-                elif [ "$Mode" == "client" ] && [ "$Route" != "policy" ] ; then
-                    ${CONFIG_DIR}wg_manager.sh $WG_INTERFACE "disable"
-                    ${CONFIG_DIR}wg_manager.sh $WG_INTERFACE
-                else
-                    Say "...in Policy mode"
-                    ${CONFIG_DIR}wg_manager.sh $WG_INTERFACE "disable" "policy"
-                    ${CONFIG_DIR}wg_manager.sh $WG_INTERFACE "policy"
-            fi
-
-            /opt/bin/wg show all
+            WG_show
             ;;
     esac
 
@@ -710,9 +670,9 @@ case "$ACTION" in
                         COLOR=$cBMAG
                         WG_INTERFACE=$(echo $LINE | awk '{print $2}')
 
-                        [ -z "$(grep -E "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)" ] && TYPE="server" || TYPE="client"
+                        [ -z "$(grep -iE "^Endpoint" ${CONFIG_DIR}${WG_INTERFACE}.conf)" ] && TYPE="server" || TYPE="client"
 
-                        # Read the Remote peer config to set the LOCAL peer endpoint
+                        # Read the Remote peer config to set the LOCAL peer Endpoint
                         if [ -f /jffs/configs/WireguardVPN_map ];then
                             LOCALIP=$(awk -v pattern="$WG_INTERFACE" 'match($0,"^"pattern) {print $2}' /jffs/configs/WireguardVPN_map)
                             SOCKET=$(awk -v pattern="$WG_INTERFACE" 'match($0,"^"pattern) {print $4}' /jffs/configs/WireguardVPN_map)
@@ -724,7 +684,7 @@ case "$ACTION" in
                         [ -n "$(echo "$LINE" | grep -E "transfer:")" ] && COLOR=$cBWHT
                     fi
 
-                    # endpoint: 209.58.188.180:51820
+                    # Endpoint: 209.58.188.180:51820
                     if [ -n "$(echo "$LINE" | grep -iE "Endpoint" )" ];then
                         # Don't get the description based on interface, but the IP socket?
                         #SOCKET=$(echo $LINE | awk '{print $2}')
@@ -736,7 +696,7 @@ case "$ACTION" in
                     if [ -n "$(echo "$LINE" | grep -iE "peer:" )" ] && [ "$TYPE" == "server" ];then
                         PUB_KEY=$(echo "$LINE" | awk '{print $2}')
                         DESC=$(grep -F "$PUB_KEY" /jffs/configs/WireguardVPN_map | grep -oE "#.*$" | sed 's/^[ \t]*//;s/[ \t]*$//')
-                        [ -z "$DESC" ] && DESC="?"
+                        [ -z "$DESC" ] && DESC="# Unidentified"
                         LINE=${COLOR}$LINE" ${cBMAG}\t('$TYPE client'  $DESC)"
                     fi
 
@@ -982,7 +942,7 @@ EOF
             for SERVER_PEER in $(wg show interfaces | grep -vE "^wg1")
                 do
                     # Is it ACTUALLY a 'server' Peer?                           # v1.08
-                    [ -n "$(grep -E "^Endpoint" ${CONFIG_DIR}${SERVER_PEER}.conf)" ] && continue || break
+                    [ -n "$(grep -iE "^Endpoint" ${CONFIG_DIR}${SERVER_PEER}.conf)" ] && continue || break
                 done
 
             PUB_SERVER_KEY=
@@ -1179,7 +1139,7 @@ EOF
     *)
 
         ShowHelp
-        echo -e $cBWHT"$VERSION v1.05 S50wireguard WireGuard Session Manager\n\n\t${cBRED}***ERROR Invalid/missing arg '$ACTION'\n"$cRESET
+        echo -e $cBWHT"$VERSION S50wireguard WireGuard Session Manager\n\n\t${cBRED}***ERROR Invalid/missing arg '$ACTION'\n"$cRESET    # v1.09
         ;;
 esac
 #) 2>&1 | logger -t $(basename $0)"[$$_***DEBUG]"
