Update S50wireguard
Change: Rename command 'genkeys' to 'create' 

Add Shell function (aka alias) 'wgm'

e.g. wgm create Nokia6310i tag="Best phone ever!"

Add QRCode support (Enware utility 'qrencode') to allow import of the Peer device configuration into the Cell-phone/Mobile

e.g.   wgm qrcode Nokia6310i

█████████████████████████████████████████████████████████████████
█████████████████████████████████████████████████████████████████
████ ▄▄▄▄▄ █ ▀  ▄▀█▄█ █▄ ▀  ▄ █▀▀▄▀█ █  ▀▄ ██▄▄▄▄█▄ ██ ▄▄▄▄▄ ████
████ █   █ █  ▀ ▀ ▀▀ ▀▄▀█ █  ▄▄   ▄▀▄█▀▄▄▄ ▀▀██▀▄ ▄ ██ █   █ ████
████ █▄▄▄█ █▀▄█ ▀▄▄▄ ▀▀▄ ▀▄▀█  ▄▄▄ █ ▄▀█▀ ▄██▄▄▄ ▄▀▄██ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀▄▀ █ █▄▀ █▄▀ █▄▀ █▄█ █▄█▄▀ ▀▄▀ █ █ █▄▀ █▄▄▄▄▄▄▄████
<snip>

diff --git a/S50wireguard b/S50wireguard
--- a/S50wireguard
+++ b/S50wireguard
@@ -1,8 +1,8 @@
 #!/bin/sh
-VERSION="v1.04"
-#============================================================================================ © 2021 Martineau v1.04
+VERSION="v1.05"
+#============================================================================================ © 2021 Martineau v1.05
 #
-#       S50wireguard   {start|stop|restart|check|CreateConfig} [ [client [policy] |server]} [wg_instance] ]
+#       S50wireguard   {start|stop|restart|check|create} [ [client [policy] |server]} [wg_instance] ]
 #
 #       S50wireguard   start 0
 #                      Initialises remote peer 'client' 'wg0'
@@ -24,7 +24,7 @@ VERSION="v1.04"
 #
 
 # Maintainer: Martineau
-# Last Updated Date: 03-Mar-2021
+# Last Updated Date: 04-Mar-2021
 #
 # Description:
 #
@@ -312,6 +312,53 @@ Check_Module_Versions() {
         echo -e $cBWHT"\n\tWireGuard Kernel and Userspace Tool up to date.\n"$cRESET
     fi
 }
+Manage_alias() {
+
+    case $1 in
+        del)
+            echo -e $cBWHT"\n\tDeleting aliases for $SCRIPT_NAME\n"$cRESET
+            sed -i "/$SCRIPT_NAME/d" /jffs/configs/profile.add
+            unalias "wgstart"
+            unalias "wgstop"
+            unalias "wgr"
+            unalias "wgd"
+            unalias "wgm"
+            echo -e $cRESET
+        ;;
+        "?")
+            # type wgstart
+            # type wgstop
+            # type wgr
+            # type wgd
+            # type wgm
+            # alias | grep $SCRIPT_NAME
+            echo -e $cRESET"\n\tAlias info not available\n"
+
+        ;;
+        *)
+        # Create Alias
+            if [ -z "$(grep "$SCRIPT_NAME" /jffs/configs/profile.add)" ];then
+                echo -e $cBWHT"\n\tCreating aliases and shell functions for $SCRIPT_NAME\n"$cRESET
+                alias wgstart='/opt/etc/init.d/$SCRIPT_NAME start'
+                echo "alias wgstart='/opt/etc/init.d/$SCRIPT_NAME start'"               >>/jffs/configs/profile.add
+
+                alias wgstop='/opt/etc/init.d/$SCRIPT_NAME stop'
+                echo "alias wgstop='/opt/etc/init.d/$SCRIPT_NAME stop'"                 >>/jffs/configs/profile.add
+
+                alias wgr='/opt/etc/init.d/$SCRIPT_NAME check'
+                echo "alias wgr='/opt/etc/init.d/$SCRIPT_NAME check'"                   >>/jffs/configs/profile.add
+
+                alias wgd='/opt/etc/init.d/$SCRIPT_NAME checkdebug'
+                echo "alias wgd='/opt/etc/init.d/$SCRIPT_NAME checkdebug'"              >>/jffs/configs/profile.add
+
+                # Shell function!
+                echo -e "wgm()  { /opt/etc/init.d/$SCRIPT_NAME \$@; }"                  >>/jffs/configs/profile.add
+            else
+                echo -e $cRED"\n\tWarning: Aliases and shell functions for $SCRIPT_NAME already exist\n"$cRESET
+            fi
+        ;;
+    esac
+}
 Create_Sample_Config() {
 
     if [ -f /jffs/configs/WireguardVPN_map ];then
@@ -367,6 +414,20 @@ Convert_Key() {
 
     echo "$KEY"
 }
+Display_QRCode() {
+
+    local FN=$1
+    local ANS=
+    local ANS=$2
+
+    if [ -f $FN ];then                                          # v1.05
+        if [ -z "$ANS" ];then
+            echo -e $cBWHT"\tPress$cBRED y$cRESET to Display QRCode for EXPORT to device '$DEVICE_NAME' ${cRESET}or press$cBGRE [Enter] to SKIP."
+            read -r "ANS"
+        fi
+        [ "$ANS" == "y" ] && { clear; qrencode -t ansiutf8 < $FN; }             # v1.05
+    fi
+}
 
 #For verbose debugging, uncomment the following two lines, and uncomment the last line of this script
 #set -x
@@ -383,6 +444,7 @@ HARDWARE_MODEL=$(Get_Router_Model)
 # v384.13+ NVRAM variable 'lan_hostname' supersedes 'computer_name'
 [ -n "$(nvram get computer_name)" ] && MYROUTER=$(nvram get computer_name) || MYROUTER=$(nvram get lan_hostname)
 BUILDNO=$(nvram get buildno)
+SCRIPT_NAME="${0##*/}"
 
 TS=$(date +"%Y%m%d-%H%M%S")    # current date and time 'yyyymmdd-hhmmss'
 
@@ -395,6 +457,8 @@ if [ "$(nvram get ntp_ready)" = "0" ];then              # Ensure event 'restart_
 #else
     #Say "$VERSION $1 WireGuard NTP is Ready"
 fi
+
+[ "$1" == "debug" ] && { shift; set -x; }
 
 ACTION=$1
 TYPE=$2
@@ -708,6 +772,7 @@ case "$ACTION" in
 
         # Create dummy 'Client' and 'Server' templates
         echo -e $cBCYA"\n\tCreating WireGuard 'Client' and 'Server' Peer templates 'wg11.conf' and wg21.conf'"$cRESET
+        opkg install qrencode
         cat > ${CONFIG_DIR}wg11.conf << EOF
 [Interface]
 #Address = 10.10.10.2/24
@@ -787,13 +852,15 @@ EOF
             # rm -rF /tmp/wireguard
         fi
 
-        # Create Alias
-        if [ -z "$(grep "S50wireguard" /jffs/configs/profile.add)" ];then
-            echo "alias wgstart='/opt/etc/init.d/S50wireguard start'"               >>/jffs/configs/profile.add
-            echo "alias wgstop='/opt/etc/init.d/S50wireguard stop'"                 >>/jffs/configs/profile.add
-            echo "alias wgr='/opt/etc/init.d/S50wireguard check'"                   >>/jffs/configs/profile.add
-            echo "alias wgd='/opt/etc/init.d/S50wireguard checkdebug'"              >>/jffs/configs/profile.add
-        fi
+        Display_QRCode "${CONFIG_DIR}wg11.conf"             # v1.05
+
+        Manage_alias
+
+        ;;
+    alias)                                                  # ['del']
+
+        Manage_alias $2                                     # v1.05
+
         ;;
     getmodules)
 
@@ -818,6 +885,16 @@ EOF
         Create_Sample_Config
 
         ;;
+    qrcode*)                                                    # {interface[.conf]}
+
+        if [ -n "$2" ];then
+            [ -z "$(echo "$2" | grep -E "\.conf$")" ] && SUFFIX=".conf"
+            [ -f  ${CONFIG_DIR}${2}${SUFFIX} ] && Display_QRCode "${CONFIG_DIR}${2}${SUFFIX}" "y" || echo -e $cBRED"\a\n\t***ERROR Invalid Peer config '${CONFIG_DIR}${2}${SUFFIX}'\n"$cRESET       # v1.05
+        else
+            echo -e $cBRED"\a\n\t***ERROR Missing/invalid Peer config\n"$cRESET
+        fi
+
+        ;;
     uninstall)
 
         echo -e $cBCYA"\n\tUninstalling Wireguard Kernel module and Userspace Tools for $HARDWARE_MODEL (v$BUILDNO)"$cBRED
@@ -838,7 +915,7 @@ EOF
 
         echo -e $cBGRE"\n\tWireGuard Uninstall complete for $HARDWARE_MODEL (v$BUILDNO)\n"$cRESET
         ;;
-    genkeys)                                                            # {name} [{tag="desciption{"}}]     # v1.03
+    create)                                                            # {name} [{tag="desciption{"}}]     # v1.03
         # Create a Private/Public key-pair for your mobile phone etc.
         #           e.g. genkeys   Nokia6310 tag="Best phone ever!"
         #
@@ -847,13 +924,41 @@ EOF
             echo -e $cBCYA"\n\tCreating Wireguard Private/Public key pair for device '$DEVICE_NAME'"$cBYEL
             wg genkey | tee ${CONFIG_DIR}${2}_private.key | wg pubkey | tee ${CONFIG_DIR}${2}_public.key
             echo -e $cBYEL"\n\tDevice '"$DEVICE_NAME"' Public key="$(cat ${CONFIG_DIR}${2}_public.key)"\n"$cRESET
-            echo -e "\tPress$cBRED y$cRESET to$cBRED ADD device '$DEVICE_NAME' ${cRESET}to 'server' Peer (wg21) or press$cBGRE [Enter] to SKIP."
+
+            # Generate the Peer config to be imported into the device
+            PUB_KEY=$(cat ${CONFIG_DIR}${DEVICE_NAME}_public.key)
+            PRI_KEY=$(cat ${CONFIG_DIR}${DEVICE_NAME}_private.key)
+            ROUTER_DDNS=$(nvram get ddns_hostname_x)
+            [ -z "$ROUTER_DDNS" ] && ROUTER_DDNS="DDNS_of_YOUR_home_$HARDWARE_MODEL"
+            CREATE_DEVICE_CONFIG="Y"
+            if [ ! -f ${CONFIG_DIR}${DEVICE_NAME}.conf ];then
+                echo -e $cRED"\a\tWarning: Peer device ${cBMAG}'$DEVICE_NAME'${cRESET}${cRED} WireGuard config already EXISTS!"
+                echo -e $cRESET"\tPress$cBRED y$cRESET to$cBRED ${aBOLD}CONFIRM${cRESET}${cBRED} Overwriting Peer device ${cBMAG}'$DEVICE_NAME.config'${cRESET} or press$cBGRE [Enter] to SKIP."
+            read -r "ANS"
+                [ "$ANS" != "y" ] && CREATE_DEVICE_CONFIG="N"
+            fi
+            if [ "$CREATE_DEVICE_CONFIG" == "Y" ];then
+                cat > ${CONFIG_DIR}${DEVICE_NAME}.conf << EOF
+#$DEVICE_NAME
+[Interface]
+PrivateKey = $PRI_KEY
+Address = 10.81.196.55/24
+DNS = 1.1.1.1
+
+[Peer]
+PublicKey = $PUB_KEY
+AllowedIPs = 0.0.0.0/0
+Endpoint = $ROUTER_DDNS:51820
+PersistentKeepalive = 25
+EOF
+
+            fi
+            echo -e $cBWHT"\tPress$cBRED y$cRESET to$cBRED ADD device '$DEVICE_NAME' ${cRESET}to 'server' Peer (wg21) or press$cBGRE [Enter] to SKIP."
             read -r "ANS"
             if [ "$ANS" == "y" ];then
                 echo -e $cBCYA"\n\tAdding device Peer '$DEVICE_NAME' to $HARDWARE_MODEL 'server' (wg21) and WireGuard config\n"
                 if [ -z "$(grep "$DEVICE_NAME" ${CONFIG_DIR}wg21.conf)" ];then
 
-                    PUB_KEY=$(cat ${CONFIG_DIR}${DEVICE_NAME}_public.key)
                     PUB_KEY=$(Convert_Key "$PUB_KEY")
 
                     DHCP_POOL=$(awk '/^wg21/ {print $3}' /jffs/configs/WireguardVPN_map | tr '/' ' ' | awk '{print $1}')
@@ -881,9 +986,12 @@ EOF
                         echo -e $cBRED"\a\n\t***ERROR 'client' Peer device$cRESET '$DEVICE_NAME'$cBRED already defined in ${cRESET}'server' (wg21)\n"$cRESET
                     fi
                 fi
-            else
-                echo -e $cBRED"\a\n\t***ERROR Missing name of client Peer device\n"$cRESET
-            fi
+
+            Display_QRCode "${CONFIG_DIR}${DEVICE_NAME}.conf"
+
+        else
+            echo -e $cBRED"\a\n\t***ERROR Missing name of client Peer device\n"$cRESET
+        fi
         ;;
     "?"|u|u" "*|uf|uf" "*)
 
@@ -925,7 +1033,9 @@ EOF
             ShowHelp
         ;;
     *)
+
         ShowHelp
+        echo -e $cBWHT"$VERSION v1.05 S50wireguard WireGuard Session Manager\n\n\t${cBRED}***ERROR Invalid/missing arg '$ACTION'\n"$cRESET
         ;;
 esac
 #) 2>&1 | logger -t $(basename $0)"[$$_***DEBUG]"
