Update wg_client
v4.01 Support SQL database for configuration parameters

diff --git a/wg_client b/wg_client
--- a/wg_client
+++ b/wg_client
@@ -1,20 +1,20 @@
 #!/bin/sh
-VERSION="v1.07"
-#============================================================================================ © 2021 Martineau v1.07
+VERSION="v4.01"
+#============================================================================================ © 2021 Martineau v4.01
 #
 
 # Maintainer: Martineau
-# Last Updated Date: 13-Mar-2021
+# Last Updated Date: 23-Mar-2021
 #
 # Description:
 #
 # Acknowledgement:
 #
-# Contributors: odkrys
+# Contributors: odkrys,@ZebMcKayhan,Torson
 
 CONFIG_DIR="/opt/etc/wireguard.d/"                 # Conform to "standards"         # v1.05 @elorimer
 INSTALL_DIR="/jffs/addons/wireguard/"
-
+SQL_DATABASE="/opt/etc/wireguard.d/WireGuard.db"        # v1.08
 
 #For verbose debugging, uncomment the following two lines, and uncomment the last line of this script
 #set -x
@@ -100,7 +100,7 @@ create_client_list(){
             ip rule add $SRCC $SRCA $DSTC $DSTA table $TARGET_LOOKUP priority $RULE_PRIO
             echo -en $cBCYA"\t"
             [ "$DSTC" == "to" ] && DSTC=" to "
-            logger -st "wireguard-${MODE}${VPN_NUM}" "Adding Wireguard 'client' Peer route for ${VPN_IP}${DSTC}$DST_IP through $TARGET_NAME"
+            logger -t "wireguard-${MODE}${VPN_NUM}" "Adding Wireguard 'client' Peer route for ${VPN_IP}${DSTC}$DST_IP through $TARGET_NAME"
             echo -en $cRESET
         fi
     done
@@ -127,21 +127,23 @@ ANSIColours
 
 FIRMWARE=$(echo $(nvram get buildno) | awk 'BEGIN { FS = "." } {printf("%03d%02d",$1,$2)}')
 
-
-
 modprobe xt_set
 modprobe xt_comment
 insmod /opt/lib/modules/wireguard 2> /dev/null
-#############################################################################EIC Hack 1 of 1################
+
 #insmod /opt/lib/modules/wireguard
 VPN_ID=$1
 [ -z "$1" ] && VPN_ID="wg0"
 [ "${VPN_ID:0:3}" == "wg1" ] && { MODE="client"; TXT="to"; } || { MODE="server"; TXT="Hosted at"; }
 VPN_NUM=${VPN_ID#"${VPN_ID%?}"}
 
+WG_INTERFACE=$VPN_ID
+
+[ -n "$(echo "$@" | grep "force")" ] && local FORCE="force"
+
 # Is this a standard 'client' Peer interface 'wg11-wg15'                    # v1.03
 if [ -z "$(echo "$VPN_ID" |  grep -oE "^wg[2][1-2]|^wg[1][1-5]*$")" ];then      # v1.03
-    # Non-stand so identfy if it's a 'client' or 'server' Peer
+    # Non-standard so identfy if it's a 'client' or 'server' Peer
     VPN_NUM="0"                 # i.e. 'client' Peer prio '990x' where the RPDB rules for 'client' Peers 'wg11'-wg15' are '991x-995x'
     if [ -f ${CONFIG_DIR}${VPN_ID}.conf ];then                                  # v1.03
         if [ -n "$(grep -E "^Endpoint" ${CONFIG_DIR}${VPN_ID}.conf)" ];then     # v1.03
@@ -156,30 +158,28 @@ if [ -z "$(echo "$VPN_ID" |  grep -oE "^wg[2][1-2]|^wg[1][1-5]*$")" ];then      
     fi
 fi
 
-############################################################################################################
-
 [ -n "$(echo "$@" | grep "policy")" ] && POLICY_MODE="in Policy Mode " || POLICY_MODE=
 
-# Read the Peer config to set the Annotation Description and LOCAL peer endpoint etc.
-if [ -f ${INSTALL_DIR}WireguardVPN.conf ];then
-    if [ "$MODE" == "client" ];then                         # v1.03
-        if [ -z "$LOCALIP" ];then
-           LOCALIP=$(awk -v pattern="${VPN_ID}" 'match($0,"^"pattern) {print $3}' ${INSTALL_DIR}WireguardVPN.conf)       # v1.03
-           export LocalIP=$LOCALIP
-        fi
-        [ -z "$SOCKET" ] && SOCKET=$(awk -v pattern="${VPN_ID}" 'match($0,"^"pattern) {print $4}' ${INSTALL_DIR}WireguardVPN.conf)
-        START_PRIO=99${VPN_NUM}0
-        END_PRIO=99${VPN_NUM}9
-        WAN_PRIO=99${VPN_NUM}0
-        VPN_PRIO=99${VPN_NUM}1
-        VPN_TBL=12$VPN_NUM
-        VPN_UNIT=$VPN_ID
-    else
-        SOCKET=$(nvram get wan_gateway)":"$(awk '/Listen/ {print $3}' ${CONFIG_DIR}${VPN_ID}.conf)      # v1.03
+# Read the database to set the Annotation Description and LOCAL peer endpoint etc.
+if [ "$MODE" == "client" ];then                         # v1.03
+    if [ -z "$LOCALIP" ];then
+       LOCALIP=$(sqlite3 $SQL_DATABASE "SELECT subnet FROM clients where peer='$WG_INTERFACE';")
+       export LocalIP=$LOCALIP
     fi
-    DESC=$(awk -v pattern="${VPN_ID}" 'match($0,"^"pattern) {print $0}' ${INSTALL_DIR}WireguardVPN.conf | grep -oE "#.*$" | sed 's/^[ \t]*//;s/[ \t]*$//')
-    [ -z "$DESC" ] && DESC="# Unidentified"
+    [ -z "$SOCKET" ] && SOCKET=$(sqlite3 $SQL_DATABASE "SELECT socket FROM clients where peer='$WG_INTERFACE';")
+    START_PRIO=99${VPN_NUM}0
+    END_PRIO=99${VPN_NUM}9
+    WAN_PRIO=99${VPN_NUM}0
+    VPN_PRIO=99${VPN_NUM}1
+    VPN_TBL=12$VPN_NUM
+    VPN_UNIT=$VPN_ID
+else
+    SOCKET=$(nvram get wan_gateway)":"$(awk '/Listen/ {print $3}' ${CONFIG_DIR}${VPN_ID}.conf)      # v1.03
 fi
+
+DESC=$(sqlite3 $SQL_DATABASE "SELECT tag FROM clients where peer='$WG_INTERFACE';")
+DESC=$(printf "%s" "$DESC" | sed 's/^[ \t]*//;s/[ \t]*$//')
+[ -z "$DESC" ] && DESC="# Unidentified"
 
 if [ "$1" != "disable" ] && [ "$2" != "disable" ];then
 
@@ -195,6 +195,13 @@ if [ "$1" != "disable" ] && [ "$2" != "disable" ];then
         #ifconfig $VPN_ID mtu 1380
         ifconfig $VPN_ID mtu 1420                           # v1.02
         ifconfig $VPN_ID txqueuelen 1000
+
+        TIMESTAMP=$(date +%s)
+        sqlite3 $SQL_DATABASE "INSERT into session values('$WG_INTERFACE','Start','$TIMESTAMP');"   # v1.08
+        sqlite3 $SQL_DATABASE "INSERT into traffic values('$WG_INTERFACE','$TIMESTAMP','0','0');"
+
+        # User Exit @Torson
+        [ -f ${INSTALL_DIR}Scripts/${VPN_ID}-route-up.sh ] && { logger -t "wireguard-${MODE}${VPN_NUM}" "Executing Event:${VPN_ID}-route-up.sh"; sh ${INSTALL_DIR}Scripts/${VPN_ID}-route-up.sh; }
 
         host="$(wg show $VPN_ID endpoints | sed -n 's/.*\t\(.*\):.*/\1/p')"
         ip route add $(ip route get $host | sed '/ via [0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/{s/^\(.* via [0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\).*/\1/}' | head -n 1) 2>/dev/null
@@ -212,11 +219,31 @@ if [ "$1" != "disable" ] && [ "$2" != "disable" ];then
             ip route add 128/1 dev $VPN_ID 2>/dev/null
         else
             #ip rule add from $(nvram get lan_ipaddr | cut -d"." -f1-3).0/24 table 12$VPN_NUM prio 99$VPN_NUM"9"
-            VPN_IP_LIST=$(awk -v pattern="${VPN_NUM}" 'match($0,"^rp1"pattern) {print $0}' ${INSTALL_DIR}WireguardVPN.conf | grep -oE "<.*$" | sed 's/^[ \t]*//;s/[ \t]*$//')
+            VPN_IP_LIST=$(sqlite3 $SQL_DATABASE "SELECT rules FROM policy WHERE peer='$WG_INTERFACE';")
 
             create_client_list
 
+            # Ipsets
+            if [ -n "$(sqlite3 $SQL_DATABASE "SELECT ipset FROM ipset WHERE peer='${WG_INTERFACE}';")" ];then
+
+                IPSETS=$(sqlite3 $SQL_DATABASE "SELECT ipset FROM ipset WHERE peer='${WG_INTERFACE}';" | tr '\n' ' ')
+                for IPSET in $IPSETS
+                    do
+                        ipset list $IPSET >/dev/null 2>&1;if [ $? -eq 0 ]; then
+                            DSTSRC=$(sqlite3 $SQL_DATABASE "SELECT dstsrc FROM ipset WHERE ipset='$IPSET' AND peer='${WG_INTERFACE}';")
+                            FWMARK=$(sqlite3 $SQL_DATABASE "SELECT fwmark FROM ipset WHERE ipset='$IPSET' AND peer='${WG_INTERFACE}';")
+                            iptables -t mangle -D PREROUTING -m set --match-set $IPSET $DSTSRC -j MARK --set-mark ${FWMARK}/${FWMARK} 2>/dev/null
+                            iptables -t mangle -A PREROUTING -m set --match-set $IPSET $DSTSRC -j MARK --set-mark ${FWMARK}/${FWMARK}
+                            logger -t "wireguard-${MODE}${VPN_NUM}" "Adding IPSet '$IPSET' route through VPN 'client' Peer" $WG_INTERFACE
+                        else
+                            logger -t "wireguard-${MODE}${VPN_NUM}" "***ERROR IPSet '$IPSET' does NOT EXIST! for routing through VPN 'client' Peer "$WG_INTERFACE
+                        fi
+                    done
+            fi
+
         fi
+
+
 
         ip route add 0/1 dev $VPN_ID table 12$VPN_NUM 2>/dev/null
         ip route add 128/1 dev $VPN_ID table 12$VPN_NUM 2>/dev/null
@@ -233,6 +260,9 @@ if [ "$1" != "disable" ] && [ "$2" != "disable" ];then
             done
 
         Firewall_delete
+
+        # User Exit @ZebMcKayhan
+        [ -f ${INSTALL_DIR}Scripts/${VPN_ID}-up.sh ] && { logger -t "wireguard-${MODE}${VPN_NUM}" "Executing Event:${VPN_ID}-up.sh"; sh ${INSTALL_DIR}Scripts/${VPN_ID}-up.sh; }
 
         iptables -t mangle -I FORWARD -o $VPN_ID -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu -m comment --comment "WireGuard 'client'"
         iptables -t mangle -I FORWARD -i $VPN_ID -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu -m comment --comment "WireGuard 'client'"
@@ -267,6 +297,9 @@ if [ "$1" != "disable" ] && [ "$2" != "disable" ];then
 
 else
 
+    # User Exit @Torson
+    [ -f ${INSTALL_DIR}Scripts/${VPN_ID}-route-down.sh ] && { logger -t "wireguard-${MODE}${VPN_NUM}" "Executing Event:${VPN_ID}-route-down.sh"; sh ${INSTALL_DIR}Scripts/${VPN_ID}-route-down.sh; }
+
     ip route del 0.0.0.0/1   dev $VPN_ID   2>/dev/null
     ip route del 128.0.0.0/1 dev $VPN_ID   2>/dev/null
     # Set the default to the last ACTIVE WireGuard interface
@@ -278,6 +311,9 @@ else
 
     ip link del dev $VPN_ID 2>/dev/null
 
+    TIMESTAMP=$(date +%s)
+    sqlite3 $SQL_DATABASE "INSERT into session values('$WG_INTERFACE','End','$TIMESTAMP');" # v1.08
+
     Firewall_delete
 
     ip rule del from $(nvram get lan_ipaddr | cut -d"." -f1-3).0/24 table 12$VPN_NUM prio 992$VPN_NUM   2>/dev/null
@@ -286,6 +322,18 @@ else
     ip rule del prio 992$VPN_NUM    2>/dev/null
 
     purge_client_list
+
+    IPSETS=$(sqlite3 $SQL_DATABASE "SELECT ipset FROM ipset WHERE peer='${WG_INTERFACE}';" | tr '\n' ' ')
+    for IPSET in $IPSETS
+        do
+            DSTSRC=$(sqlite3 $SQL_DATABASE "SELECT dstsrc FROM ipset WHERE ipset='$IPSET' AND peer='${WG_INTERFACE}';")
+            FWMARK=$(sqlite3 $SQL_DATABASE "SELECT fwmark FROM ipset WHERE ipset='$IPSET' AND peer='${WG_INTERFACE}';")
+            iptables -t mangle -D PREROUTING -m set --match-set $IPSET $DSTSRC -j MARK --set-mark ${FWMARK}/${FWMARK} 2>/dev/null
+            logger -t "wireguard-${MODE}${VPN_NUM}" "Removing IPSet '$IPSET' routing through VPN 'client' Peer" $WG_INTERFACE
+        done
+
+    # User Exit @ZebMcKayhan
+    [ -f ${INSTALL_DIR}Scripts/${VPN_ID}-up.sh ] && { logger -t "wireguard-${MODE}${VPN_NUM}" "Executing Event:${VPN_ID}-down.sh"; sh ${INSTALL_DIR}Scripts/${VPN_ID}-down.sh; }
 
 #############################################################################EIC Hack 5 of 7################
         #ipset -F $Nipset 2>/dev/null
@@ -297,7 +345,7 @@ else
     #service restart_dnsmasq
     #service restart_dnsmasq 2>&1 1>/dev/null
     logger -t "wireguard-${MODE}${VPN_NUM}" "Wireguard VPN '$MODE' Peer ($VPN_ID) $TXT $SOCKET ($DESC) Terminated"
-    echo -e $cBGRE"\twireguard-${MODE}${VPN_NUM}: Wireguard VPN '$MODE' Peer (${cBMAG}$VPN_ID${cBGRE}) $TXT $SOCKET (${cBMAG}$DESC${cBGRE}) ${cBRED}${aREVERSE}Terminated"$cRESET
+    echo -e $cBGRE"\twireguard-${MODE}${VPN_NUM}: Wireguard VPN '$MODE' Peer (${cBMAG}$VPN_ID${cBGRE}) $TXT $SOCKET (${cBMAG}$DESC${cBGRE}) ${cBRED}Terminated"$cRESET
     echo -e $cRESET
 fi
 
